language: python
env:
  - TOXENV=py34
  - TOXENV=py27
  - TOXENV=cover
install:
  - travis_retry pip install codecov
  - travis_retry pip install tox
script:
  - travis_retry tox
after_success:
    codecov